[package]
name = "rust_actix"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
serde = { version = "1.0.208", features = ["derive"] }
serde_json = "1.0.125"
env_logger = "0.11.5"
dotenv = "0.15.0"
lazy_static = "1.5.0"