version: "3.8"
services:
  subscription_postgres:
    platform: linux/x86_64
    image: postgres:latest
    container_name: subscription_postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    volumes:
      - ./postgresql:/docker-entrypoint-initdb.d
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - subscription_network

  subscription_redis:
    image: redis:latest
    container_name: subscription_redis
    ports:
      - "6379:6379"
    networks:
      - subscription_network

  subscription_server:
    platform: linux/amd64
    container_name: subscription_server
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: sh -c "cargo watch -x fmt -s 'mold -run cargo run'"
    volumes:
      - .:/app
      - cargo-registry:/usr/local/cargo/registry
      - cargo-git:/usr/local/cargo/git
      - target:/app/target
    environment:
      RUST_LOG: "actix_web=info"
      REDIS_URL: "redis://subscription_redis:6379"
      ADDRESS: 0.0.0.0
      PORT: 8080
      DATABASE_URL: "postgres://postgres@subscription_postgres:5432/subscription_db"
    ports:
      - "8080:8080"
    depends_on:
      - subscription_postgres
      - subscription_redis
    networks:
      - subscription_network

networks:
  subscription_network:

volumes:
  cargo-registry:
  cargo-git:
  target: